import { getPages } from "@/sanity/sanity.utils";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  console.log("pages: ", pages);
  return (
    <html lang="en">
      <body>
        {/* <NavBar pages={pages} /> */}
        <header className="flex gap-3">
          {pages.map((page) => (
            <nav key={page._id}>{page.name}</nav>
          ))}
        </header>
        {children}
      </body>
    </html>
  );
}
