import { getPages } from "@/sanity/sanity.utils";
import "../globals.css";
import Link from "next/link";
import NavBar from "../components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  console.log("pages: ", pages);
  return (
    <html lang="en">
      <body>
        <header className="flex px-5 py-3 text-gray-600    gap-3 justify-between  items-center">
          <div>
            <Link href="/" className="font-bold text-3xl">
              CMS
            </Link>
          </div>

          <NavBar pages={pages} />
        </header>
        {children}
      </body>
    </html>
  );
}
