import { getPages } from "@/sanity/sanity.utils";
import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  console.log("pages: ", pages);
  return (
    <html lang="en">
      <body>
        {/* <NavBar pages={pages} /> */}
        <header className="flex px-5 py-3   gap-3 justify-between ">
          <div>
            <h1 className="font-bold text-3xl">CMS</h1>
          </div>
          <nav className="space-x-3">
            {pages.map((page) => (
              <Link
                href={`/${page.slug}`}
                key={page._id}
                className="font-bold hover:scale-105 transition"
              >
                {page.name}
              </Link>
            ))}
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
